---
default:
  repeat_times: 1
  repeat_pause: 0
  consumer_type: BaseConsumer
  topic: test_topic1
  consumer_config:
    bootstrap.servers: localhost:9092
    group.id: 'benchmark_consumer_group'
    auto.offset.reset: smallest
    enable.auto.commit: false
    session.timeout.ms: 6000

scenarios:
  10B_full_topic:
    topic: benchmark_topic_10B
    message_limit: -1

  1KB_one_million:
    consumer_type: BaseConsumer
    topic: benchmark_topic_1KB
    message_limit: 1000000

  one_million_stream:
    consumer_type: StreamConsumer
    message_limit: 1000000
