---
scenarios:
  byte_bursts:
    repeat_times: 3
    repeat_pause: 20
    topic: test_topic
    message_size: 10000
    message_count: 200000
    threads: 6
    producer_config:
      bootstrap.servers: localhost:9092
      queue.buffering.max.ms: 100
  msg_bursts:
    repeat_times: 3
    repeat_pause: 10
    topic: test_topic
    message_size: 10
    message_count: 20000000
    threads: 6
    producer_config:
      bootstrap.servers: localhost:9092
      queue.buffering.max.messages: 1000000
      queue.buffering.max.ms: 100
  byte_no_pause:
    repeat_times: 5
    topic: test_topic
    message_size: 10000
    message_count: 300000
    threads: 6
    producer_config:
      bootstrap.servers: localhost:9092
      queue.buffering.max.ms: 100
  msg_no_pause:
    repeat_times: 5
    topic: test_topic
    message_size: 10
    message_count: 10000000
    threads: 6
    producer_config:
      bootstrap.servers: localhost:9092
      queue.buffering.max.messages: 1000000
      queue.buffering.max.ms: 100
  short:
    repeat_times: 1
    topic: test_topic
    message_size: 64
    message_count: 1000
    producer_config:
      bootstrap.servers: localhost:9092
      queue.buffering.max.messages: 1000000
      queue.buffering.max.ms: 100
